In [1]:
#Q1 Import the "numpy" library as "np".
import numpy as np

In [3]:
#Q2 Create an array of shape (2, 3, 4) of zeros.
np.zeros((2,3,4))


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [5]:
#Q3 Create an array of shape (2, 3, 4) of ones
np.ones((2,3,4), dtype="int32")

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [6]:
#Q4  Create an array with values 0 to 999 using the "np.arange" function
arr = np.arange(0,100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
#Q5 Create an array from the list [2, 3.2, 5.5, -6.4, -2.2, 2.4] and assign it to the variable "a"
l = [2,3.2,5.5,-6.4,-2.2,2.4]
a = np.array(l)
a

array([ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4])

In [8]:
#Q6 Do you know what a[1] will equal? Print it to see
a[1]

3.2

In [9]:
#Q7 Try printing a[1:4] to see what that equals
a[1:4]

array([ 3.2,  5.5, -6.4])

In [11]:
#Q8 Create a 2-D array from the following list and assign it to the variable "a": [[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]]
l = [[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]]
print(l)
a = np.array(l)
a

[[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]]


array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [12]:
#Q9 Can you guess what the following slices are equal to? Print them to check your understanding. a[:, 3] a[1:4, 0:4] a[1:, 2]
print(a[:, 3])
print(a[1:4, 0:4])
print(a[1:, 2])

[-6.4  0.1 21. ]
[[ 1.  22.   4.   0.1]
 [ 3.   1.   2.1 21. ]]
[4.  2.1]


In [13]:
#Q10 Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the variable "arr".Print the shape of the array. Print the size of the array. Print the maximum and minimum of the array
list1 = np.arange(4)
list2= np.arange(10,14)
arr = np.array([list1,list2])
arr

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [14]:
print(arr.shape)

(2, 4)


In [15]:
arr.size

8

In [16]:
np.max(arr)

13

In [17]:
np.min(arr)

0

In [4]:
import numpy as np
arr = np.array([[0,1,2,3],[10,11,12,13]])
arr

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [11]:
#Q11 Continue to use the array "arr" as defined above.Print the array re-shaped to (2, 2, 2).Print the array transposed.Print the array flattened to a single dimension. Print the array converted to floats.



In [7]:
arr.reshape(2,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[10, 11],
        [12, 13]]])

In [8]:
k = arr.T
k

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [9]:
f = np.ravel(arr)
f

array([ 0,  1,  2,  3, 10, 11, 12, 13])

In [10]:
b = arr.astype("float32")
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.]], dtype=float32)

In [12]:
#Q12 Create an an array counting from 1 to 20 inclusive
arr1 = np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
#Q13 The array of multiples of 3 greater than 0 and less than 30
arr2 = np.arange(1,31)
arr2[::3]

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])